name:                dsmr-metrics
version:             0.1.0.0
github:              "githubuser/dsmr-metrics"
license:             BSD3
author:              "Arjen Langebaerd"
maintainer:          "arjen@langebaerd.net"
copyright:           "2020 AArjen Langebaerd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dsmr-metrics#readme>

dependencies:
- base >= 4.13 && < 4.14
- text >= 1.2.4.0 && < 1.3
- wai-middleware-prometheus >= 1 && < 1.1
- prometheus-client >=1.0.0.1 && < 1.1
- prometheus-metrics-ghc >=1.0.1 && < 1.1
- warp >= 3.3.12 && < 3.4
- http-types >= 0.12.3 && < 0.13
- bytestring >= 0.10.10.0 && < 0.11
- wai >= 3.2.2.1 && < 3.3
- async >= 2.2.2 && < 2.3
- time >= 1.9.3 && < 1.10
- megaparsec >= 8.0.0 && < 8.1
- lens >=4.18.1 && < 4.19
- safe >=0.3.19 && < 0.4
- polysemy >= 1.3.0.0 && < 1.4
- polysemy-plugin >=0.2.5.0 && < 0.3
 
default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - TemplateHaskell

library:
  source-dirs: src

executables:
  dsmr-metrics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-T -N"'
    - -fplugin=Polysemy.Plugin
    - -O2 
    - -flate-specialise 
    - -fspecialise-aggressively
    - -Wall
    #- -Werror
    dependencies:
    - dsmr-metrics

tests:
  dsmr-metrics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    - -Wall
   # - -Werror
    dependencies:
    - dsmr-metrics
    - hspec >=2.7.1 && < 2.8
    - QuickCheck >= 2.13.2 && <2.14
    - deepseq >= 1.4.4.0 && < 1.5
    - hedgehog >= 1.0.2 && < 1.1.0
