name:                dsmr-metrics
version:             0.1.0.0
github:              "githubuser/dsmr-metrics"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dsmr-metrics#readme>

dependencies:
- base >= 4.7 && < 5
- wai-middleware-prometheus >= 1 && < 2
- prometheus-client >=1.0.0.1 && < 2
- prometheus-metrics-ghc >=1.0.1 && < 2
- warp >= 3.3.12 && < 4

library:
  source-dirs: src

executables:
  dsmr-metrics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dsmr-metrics

tests:
  dsmr-metrics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dsmr-metrics
